config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	root 'orders#new'
  # root 'statics#coming_soon'

  resources :delivery_points
  resources :promo_codes

  get 'coming_soon', to: 'statics#coming_soon'
	get 'ourstory', to: 'statics#ourstory'
	get 'thankyou', to: 'statics#thankyou', as: :thankyou
	get 'contactus', to: 'statics#contactus'
	get 'tpi', to: 'statics#tpi'

	get 'admin_order', to: 'orders#admin_order'

	resources :products
	resources :users
	resources :expenses
	
	resources :orders do
		get 'assign', 'deliver', 'cancel'
	end

  get 'order', to: 'statics#order'

	get 'ongoing', to: 'orders#ongoing', as: :ongoing

	get 'myorders', to: 'users#myorders', as: :myorders

	get 'login', to: 'sessions#new'
	post 'login', to: 'sessions#create'
	delete 'logout', to: 'sessions#destroy'

  post 'promo_codes/apply', to: 'promo_codes#apply', as: :promo_codes_apply

  get 'analytics/date_range', to: 'analytics#date_range', as: :analytics_date_range
  post 'analytics/date_range', to: 'analytics#date_range'
end

app/models/promo_code.rb
class PromoCode < ApplicationRecord
  validates :name, :promo_type, :discount_value, :minimum_amount, :expiration_date, presence: true

  enum promo_type: { flat_discount: 0, percentage_discount: 1 }

  def self.calculate(promo_code_name:, subtotal:)
    promo_code = PromoCode.find_by_name(promo_code_name)
    error_messages = []

    error_messages << 'Please input promo code' if promo_code_name.empty?
    error_messages << 'Promo code not found' if promo_code.nil?
    error_messages << 'Promo code expired' if promo_code.present? && promo_code.expiration_date < Time.now

    if promo_code.present? && subtotal < promo_code.minimum_amount
      # error_messages << "Minimum order amount for this promo code is #{@promo_code.minimum_amount} TK"
      error_messages << "Please order minimum #{promo_code.minimum_amount} TK to use this promo code"
    end

    discount = 0
    total = subtotal

    if error_messages.empty?
      if promo_code.flat_discount?
        discount = promo_code.discount_value
      elsif promo_code.percentage_discount?
        discount = subtotal * (promo_code.discount_value / 100.0)
      end    
    end

    total = subtotal - discount

    return promo_code, error_messages, discount, total
  end
end

app/controllers/promo_codes_controller.rb
class PromoCodesController < ApplicationController
  before_action :set_promo_code, only: [:show, :edit, :update, :destroy]

  # GET /promo_codes
  # GET /promo_codes.json
  def index
    @promo_codes = PromoCode.all
  end

  # GET /promo_codes/1
  # GET /promo_codes/1.json
  def show
  end

  # POST /promo_codes/apply
  def apply
    # @promo_code = PromoCode.find_by_name(params[:promo_code])
    # error_messages = []

    # error_messages << 'Please input promo code' if params[:promo_code].empty?
    # error_messages << 'Promo code not found' if @promo_code.nil?
    # error_messages << 'Promo code expired' if @promo_code.present? && @promo_code.expiration_date < Time.now

    # if @promo_code.present? && params[:subtotal_amount].to_i < @promo_code.minimum_amount
    #   # error_messages << "Minimum order amount for this promo code is #{@promo_code.minimum_amount} TK"
    #   error_messages << "Please order minimum #{@promo_code.minimum_amount} TK to use this promo code"
    # end

    subtotal = params[:subtotal_amount].to_i
    promo_hash = { promo_code_name: params[:promo_code], subtotal: subtotal }
    @promo_code, error_messages, discount, total = PromoCode.calculate(promo_hash)

    if error_messages.empty?
      render json: { promo_code: @promo_code.as_json, subtotal: subtotal, 
                     discount: discount, total: total, status: 200 }, status: :ok
    else
      render json: { error_messages: error_messages, status: 202 }, status: 202
    end
  end

  # GET /promo_codes/new
  def new
    @promo_code = PromoCode.new
  end

  # GET /promo_codes/1/edit
  def edit
  end

  # POST /promo_codes
  # POST /promo_codes.json
  def create
    @promo_code = PromoCode.new(promo_code_params)

    respond_to do |format|
      if @promo_code.save
        format.html { redirect_to @promo_code, notice: 'Promo code was successfully created.' }
        format.json { render :show, status: :created, location: @promo_code }
      else
        format.html { render :new }
        format.json { render json: @promo_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /promo_codes/1
  # PATCH/PUT /promo_codes/1.json
  def update
    respond_to do |format|
      if @promo_code.update(promo_code_params)
        format.html { redirect_to @promo_code, notice: 'Promo code was successfully updated.' }
        format.json { render :show, status: :ok, location: @promo_code }
      else
        format.html { render :edit }
        format.json { render json: @promo_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /promo_codes/1
  # DELETE /promo_codes/1.json
  def destroy
    @promo_code.destroy
    respond_to do |format|
      format.html { redirect_to promo_codes_url, notice: 'Promo code was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_promo_code
      @promo_code = PromoCode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def promo_code_params
      params.require(:promo_code).permit(:name, :promo_type, :discount_value, :minimum_amount, :expiration_date)
    end
end

app/helpers/promo_codes_helper.rb
module PromoCodesHelper
end

app/views/promo_codes/_form.html.erb
<%= form_with(model: promo_code, local: true) do |form| %>
  <% if promo_code.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(promo_code.errors.count, "error") %> prohibited this promo_code from being saved:</h2>

      <ul>
      <% promo_code.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :promo_type %>
    <%#= form.number_field :promo_type %>
    <% promo_types = [] %>
    <% PromoCode.promo_types.each { |item, key| promo_types << [item.humanize, item] } %>
    <% promo_types_options = options_for_select(promo_types, selected: promo_code.promo_type) %>
    <%= form.select(:promo_type, promo_types_options, { prompt: '-- please select --' }, {}) %>
  </div>

  <div class="field">
    <%= form.label :discount_value %>
    <%= form.number_field :discount_value %>
  </div>

  <div class="field">
    <%= form.label :minimum_amount %>
    <%= form.number_field :minimum_amount %>
  </div>

  <div class="field">
    <%= form.label :expiration_date %>
    <%= form.datetime_select :expiration_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/promo_codes/edit.html.erb
<div class="container">
  <div class="py-4">
    <h1 class="semi">Editing Promo Code</h1>
    <hr>
  </div>

  <%= render 'form', promo_code: @promo_code %>

  <%= link_to 'Show', @promo_code %> |
  <%= link_to 'Back', promo_codes_path %>

</div>

app/views/promo_codes/index.html.erb
<div class="container">
  <div class="py-4">
    <h1 class="semi">Promo Codes</h1>
    <hr>
  </div>

  <table id="all-orders-table" class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Promo type</th>
        <th>Discount value</th>
        <th>Minimum amount</th>
        <th>Expiration date</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @promo_codes.each do |promo_code| %>
        <tr>
          <td><h3><span class="text-info"><%= promo_code.name %></span></h3></td>
          <td><%= promo_code.promo_type.humanize %></td>
          <td><%= promo_code.discount_value %></td>
          <td><%= promo_code.minimum_amount %></td>
          <td>
            <div class="mb-1"><%= promo_code.expiration_date.strftime("%I:%M %p") %></div>
            <div><%= promo_code.expiration_date.strftime("%a, %d %b %Y") %></div>    
          </td>
          <td><%= link_to 'Show', promo_code, class: 'btn btn-sm btn-warning' %></td>
          <td><%= link_to 'Edit', edit_promo_code_path(promo_code), class: 'btn btn-sm btn-info' %></td>
          <td>
            <%= link_to 'Destroy', promo_code, method: :delete, 
                data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Promo Code', new_promo_code_path, class: 'btn btn-sm btn-primary' %>

</div>

app/views/promo_codes/new.html.erb
<div class="container">
  <div class="py-4">
    <h1 class="semi">New Promo Code</h1>
    <hr>
  </div>

  <%= render 'form', promo_code: @promo_code %>

  <%= link_to 'Back', promo_codes_path %>

</div>

app/views/promo_codes/show.html.erb
<div class="container">
  <div class="py-4">
    <h1 class="semi">Show Promo Code</h1>
    <hr>
  </div>

  <p>
    <strong>Id:</strong>
    <%= @promo_code.id %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= @promo_code.name %>
  </p>

  <p>
    <strong>Promo type:</strong>
    <%= @promo_code.promo_type.humanize %>
  </p>

  <p>
    <strong>Discount value:</strong>
    <%= @promo_code.discount_value %>
  </p>

  <p>
    <strong>Minimum amount:</strong>
    <%= @promo_code.minimum_amount %>
  </p>

  <p>
    <strong>Expiration date:</strong>
    <%= @promo_code.expiration_date.strftime("%I:%M %p - %a, %d %b %Y") %>
  </p>

  <%= link_to 'Edit', edit_promo_code_path(@promo_code) %> |
  <%= link_to 'Back', promo_codes_path %>

</div>