config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	root 'orders#new'
  # root 'statics#coming_soon'

  resources :delivery_points
  resources :promo_codes

  get 'coming_soon', to: 'statics#coming_soon'
	get 'ourstory', to: 'statics#ourstory'
	get 'thankyou', to: 'statics#thankyou', as: :thankyou
	get 'contactus', to: 'statics#contactus'
	get 'tpi', to: 'statics#tpi'

	get 'admin_order', to: 'orders#admin_order'

	resources :products
	resources :users
	resources :expenses
	
	resources :orders do
		get 'assign', 'deliver', 'cancel'
	end

  get 'order', to: 'statics#order'

	get 'ongoing', to: 'orders#ongoing', as: :ongoing

	get 'myorders', to: 'users#myorders', as: :myorders

	get 'login', to: 'sessions#new'
	post 'login', to: 'sessions#create'
	delete 'logout', to: 'sessions#destroy'

  post 'promo_codes/apply', to: 'promo_codes#apply', as: :promo_codes_apply

  get 'analytics/date_range', to: 'analytics#date_range', as: :analytics_date_range
  post 'analytics/date_range', to: 'analytics#date_range'
end

app/models/delivery_point.rb
class DeliveryPoint < ApplicationRecord
  has_many :products
  has_many :orders
  has_many :expenses
  belongs_to :manager, class_name: 'User', optional: true
end

app/controllers/delivery_points_controller.rb
class DeliveryPointsController < ApplicationController
  before_action :require_admin, except: [:index]
  before_action :set_delivery_point, only: [:show, :edit, :update, :destroy]

  # GET /delivery_points
  # GET /delivery_points.json
  def index
    if is_admin?
      @delivery_points = DeliveryPoint.all
    else
      @delivery_points = current_user.delivery_points
    end
  end

  # GET /delivery_points/1
  # GET /delivery_points/1.json
  def show
  end

  # GET /delivery_points/new
  def new
    @delivery_point = DeliveryPoint.new
  end

  # GET /delivery_points/1/edit
  def edit
  end

  # POST /delivery_points
  # POST /delivery_points.json
  def create
    @delivery_point = DeliveryPoint.new(delivery_point_params)

    respond_to do |format|
      if @delivery_point.save
        format.html { redirect_to @delivery_point, notice: 'Delivery point was successfully created.' }
        format.json { render :show, status: :created, location: @delivery_point }
      else
        format.html { render :new }
        format.json { render json: @delivery_point.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /delivery_points/1
  # PATCH/PUT /delivery_points/1.json
  def update
    respond_to do |format|
      if @delivery_point.update(delivery_point_params)
        format.html { redirect_to @delivery_point, notice: 'Delivery point was successfully updated.' }
        format.json { render :show, status: :ok, location: @delivery_point }
      else
        format.html { render :edit }
        format.json { render json: @delivery_point.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /delivery_points/1
  # DELETE /delivery_points/1.json
  # def destroy
  #   @delivery_point.destroy
  #   respond_to do |format|
  #     format.html { redirect_to delivery_points_url, notice: 'Delivery point was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_delivery_point
      @delivery_point = DeliveryPoint.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def delivery_point_params
      params.require(:delivery_point).permit(:name, :manager_id)
    end
end

app/helpers/delivery_points_helper.rb
module DeliveryPointsHelper
end

app/views/delivery_points/_form.html.erb
<%= form_with(model: delivery_point, local: true) do |form| %>
  <% if delivery_point.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(delivery_point.errors.count, "error") %> prohibited this delivery_point from being saved:</h2>

      <ul>
      <% delivery_point.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="form-group">
    <%= form.label :manager_id %>

    <% users_array = User.all.map { |user| [user.name, user.id] } %>
    <% manager_options = options_for_select(users_array, selected: delivery_point.manager_id) %>
    <%= form.select :manager_id, manager_options, { prompt: '-- please select --' }, class: '' %>
  </div>

  <div class="actions form-group">
    <%= form.submit class: 'btn btn-sm btn-primary' %>
  </div>
<% end %>

app/views/delivery_points/edit.html.erb
<div class="container">

  <div class="py-4">
    <h1 class="semi">Editing Delivery Point</h1>
    <hr>
  </div>

  <%= render 'form', delivery_point: @delivery_point %>

  <%= link_to 'Show', @delivery_point %> |
  <%= link_to 'Back', delivery_points_path %>

</div>

app/views/delivery_points/index.html.erb
<div class="container">

  <div class="py-4">
    <h1 class="semi">Delivery Points</h1>
    <hr>
  </div>

  <table id="all-orders-table" class="table">
    <thead>
      <tr>
        <th>Id</th>
        <th>Name</th>
        <th></th>

        <% if is_admin? %>
        <th></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% @delivery_points.each do |delivery_point| %>
        <tr>
          <td><%= delivery_point.id %></td>
          <td>
            <div><%= delivery_point.name %></div>
            
            <% if delivery_point.manager_id == current_user.id %>
              <div class="pt-1">
                <span class="badge badge-info badge-pill">You are manager</span>
              </div>
            <% end  %>
          </td>
          
          <td>

            <ul class="list-group list-group-flush">
              <li class="list-group-item">
                <%= link_to 'Ongoing Orders', ongoing_path(delivery_point_id: delivery_point.id),
                      class: 'btn btn-sm btn-primary' %>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center">
                <%= link_to 'Products', products_path(delivery_point_id: delivery_point.id) %>
                <span class="badge badge-info badge-pill"><%= delivery_point.products.count %></span>
              </li>
              <li class="list-group-item"><%= link_to 'Expenditure', expenses_path(delivery_point_id: delivery_point.id) %></li>
              
            </ul> 
          </td>
          
          <% if is_admin? %>
            <td>
              <div class="pt-2 pb-2">
                <strong>Manager:</strong>
                <% if delivery_point.manager.present? %>
                  <%= delivery_point.manager.name %>
                <% else %>
                  Not assigned
                <% end %>
              </div>

              <div class="pb-3">
                <a href="<%= analytics_date_range_path(delivery_point_id: delivery_point.id) %>" class="btn btn-sm btn-primary">
                  <i class="fa fa-chart-line"></i> Analyitics
                </a>
              </div>

              <%= link_to 'Edit', edit_delivery_point_path(delivery_point), class: 'btn btn-sm btn-warning' %>
              <%#= link_to 'Destroy', delivery_point, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <% if is_admin? %>
    <br> 
    <%= link_to 'New Delivery Point', new_delivery_point_path, class: 'btn btn-sm btn-primary' %>
  <% end %>

</div>

app/views/delivery_points/new.html.erb
<div class="container">

  <div class="py-4">
    <h1 class="semi">New Delivery Point</h1>
    <hr>
  </div>

  <%= render 'form', delivery_point: @delivery_point %>

  <%= link_to 'Back', delivery_points_path %>

</div>

app/views/delivery_points/show.html.erb
<div class="container">

  <div class="py-4">
    <h1 class="semi">Show Delivery Point</h1>
    <hr>
  </div>

  <p>
    <strong>Id:</strong>
    <%= @delivery_point.id %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= @delivery_point.name %>
  </p>

  <p>
    <strong>Manager:</strong>
    <% if @delivery_point.manager.present? %>
      <%= @delivery_point.manager.name %>
    <% else %>
      Not assigned
    <% end %>
  </p>

  <%= link_to 'Edit', edit_delivery_point_path(@delivery_point) %> |
  <%= link_to 'Back', delivery_points_path %>

</div>