config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	root 'orders#new'
  # root 'statics#coming_soon'

  resources :delivery_points
  resources :promo_codes

  get 'coming_soon', to: 'statics#coming_soon'
	get 'ourstory', to: 'statics#ourstory'
	get 'thankyou', to: 'statics#thankyou', as: :thankyou
	get 'contactus', to: 'statics#contactus'
	get 'tpi', to: 'statics#tpi'

	get 'admin_order', to: 'orders#admin_order'

	resources :products
	resources :users
	resources :expenses
	
	resources :orders do
		get 'assign', 'deliver', 'cancel'
	end

  get 'order', to: 'statics#order'

	get 'ongoing', to: 'orders#ongoing', as: :ongoing

	get 'myorders', to: 'users#myorders', as: :myorders

	get 'login', to: 'sessions#new'
	post 'login', to: 'sessions#create'
	delete 'logout', to: 'sessions#destroy'

  post 'promo_codes/apply', to: 'promo_codes#apply', as: :promo_codes_apply

  get 'analytics/date_range', to: 'analytics#date_range', as: :analytics_date_range
  post 'analytics/date_range', to: 'analytics#date_range'
end

app/models/user.rb
class User < ApplicationRecord
	has_many :orders
	has_secure_password

  validates :name, :username, presence: true
  validates :username, uniqueness: true

  enum order_connection_status: { connected_to_order: 1, not_connected_to_order: 0 }

  has_many :delivery_points, foreign_key: :manager_id

  def get_api_token
    reset_api_token if self.api_token.nil?
    self.api_token
  end

  def reset_api_token
    api_token = generate_unique_api_token
    self.update_attribute(:api_token, api_token)
  end

  def generate_unique_api_token
    loop do
      token = (SecureRandom.base64(10).tr('+/=', 'xyz') + '-' + DateTime.now.to_s).parameterize
      break token unless User.where(api_token: token).exists?
    end
  end

  def set_order_connection_status(online:)
    self.update_attribute(:order_connection_status, online)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_timezone
	before_action :require_user, except: [:new, :create]

	def index
		@users = User.all
	end

	def myorders
		@user = User.find(session[:user_id]) if session[:user_id]
		@myorders = @user.orders.where('status=? OR status=?', 'Pending', 'On The Way')
	end

	def edit
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to users_path
		else
			render 'new'
		end
	end

	def show
		@user = User.find(params[:id])
	end
	
	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			# flash[:notice] = "Updated"
			redirect_to users_path
		else
			render 'new'
		end
	end
	
	def destroy
		@user = User.find(params[:id])
		@user.destroy
		redirect_to users_path
	end

	private
	def user_params 
		params.require(:user).permit(:username, :name, :password, :admin)
	end
	def set_timezone
		Time.zone = "Dhaka"
	end
end

app/views/users/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-12 py-4">
			<h1 class="semi">Edit User Details</h1>
			<hr>
		</div>
		<hr>
	</div>

	<div class="row">
		<div class="col-md-5 col-12">
			<%= form_for @user do |f| %>

				<div class="form-group row">
					<label class="col-3 col-form-label">Name</label>
					<div class="col">
						<%= f.text_field :name, class: "form-control", :required => true %>
					</div>
				</div>

				<div class="form-group row">
					<label class="col-3 col-form-label">Username</label>
					<div class="col">
						<%= f.text_field :username, class: "form-control" %>
					</div>
				</div>

				<div class="form-group row">
					<label class="col-3 col-form-label">Password</label>
					<div class="col">
						<%= f.password_field :password, class: "form-control", :required => true %>
					</div>
				</div>

				<div class="custom-control custom-switch mb-4">
					<%= f.check_box :admin, :value => true, class: "custom-control-input", id: "customSwitch1" %>
				  <label class="custom-control-label" for="customSwitch1">Admin Access</label>
				</div>

				<%= f.submit class: "btn btn-success btn-sm" %>

			<% end %>	
		</div>
	</div>
</div>

app/views/users/index.html.erb
<div class="container table-container">
	<div class="row">
		<div class="col-12 py-4">
			<h1 class="semi">All Users</h1>
			<%= link_to "Create New User", new_user_path, :class => "btn btn-outline-primary" %>
			<hr>
		</div>
		<hr>
		<div class="col-12">
			<table id="all-orders-table" class="display">
				<thead>
					<tr>
						<th>ID</th>
						<th>Name</th>
						<th>Username</th>
						<th>Admin</th>
						<th>Actions</th>
					</tr>
				</thead>
				<tbody>
					<% @users.each do |user| %>
					<tr>
						<td><%= user.id %></td>
						<td><%= user.name %></td>
						<td><%= user.username %></td>
						<td><%= user.admin? %></td>
						<td>
							<%= link_to 'Edit', edit_user_path(user), class: 'btn btn-sm btn-warning' %>
	                        <%= link_to 'Delete', user_path(user), method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-sm btn-danger disabled' %>
						</td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/users/myorders.html.erb
<div class="container table-container order-cable-here" datapage="myorders" datapointid="">
	<div class="row">
		<div class="col-12 py-4">
			<h1 class="semi">My Orders <span class="realtime-status">Realtime: <span id="realtime-status-message">Connecting...</span></span></h1>

      <h1 class="btn btn-warning" id="enable-notification-sound">Enable Notification Sound</h1>

      <hr>
		</div>
		<hr>
		<div class="col-12" style="overflow-x: scroll;">
			<table id="all-orders-table" class="display">
				<thead>
					<tr>
            <th>ID</th>
						<th>Name</th>
						<th>Address</th>
						<th>Order Details</th>
						<th>Status</th>
						<th>Actions</th>
					</tr>
				</thead>
				<tbody>
					<% @myorders.each do |order| %>
					<tr>
			      <td><%= order.id %></td>
						<td><%= order.fullname %> <span class="badge badge-pill badge-primary"><%= order.existing %></span></td>
						<td>
							Address : <%= order.address %><br> 
							Flat/House : <%= order.flathouse %><br>
							Road : <%= order.road %><br>
              Instruction : <%= order.instructions %>
						</td>
						<td>
							<% order.itemquantity.to_s.split("-").each do |i| %>
								<p class="semi mb-0"><%= i.split(".")[1] + "x " + i.split(".")[0] rescue '---' %></p>
							<% end %>

              <hr class="my-1">
              <p class="m-0">Subtotal : <%= order.subtotal %></p>
              <p class="m-0">Discount <%= "( #{order.promo_discount_value}% )" if order.percentage_discount? %> : <%= order.discount %></p>

							<hr class="my-1">
							<p class="semi m-0">Total : <%= order.total %></p>
						</td>
						<td><%= order.status %></td>
						<td>
							<%= link_to 'Call', "tel:#{order.phone}", class: 'btn btn-sm btn-warning' %>
	                        
	                        <% if order.latlng.present? %>
		                        <a class="btn btn-sm btn-primary" href="https://www.google.com/maps/?q=<%= order.latlng %>">Navigate</a>
		                    <% end %>
		                    <%= link_to 'Deliver', order_deliver_path(order), class: 'btn btn-sm btn-success' %>
						</td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>

</div>


<%# content_for :user_javascript do %>
  <%#= render partial: '/layouts/cable/order_cable_js' %>
<%# end %>

app/views/users/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-12 py-4">
			<h1 class="semi">New User Sign Up</h1>
			<hr>
		</div>
		<hr>
	</div>

  <div>
    <% if @user.errors.any? %>
    <div class="text-danger">
      <h6><%= pluralize(@user.errors.count, "error") %>:</h6>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  </div>

	<div class="row">
		<div class="col-md-5 col-12">
			<%= form_for @user do |f| %>

				<div class="form-group row">
					<label class="col-3 col-form-label">Name</label>
					<div class="col">
						<%= f.text_field :name, class: "form-control", :required => true %>
					</div>
				</div>

				<div class="form-group row">
					<label class="col-3 col-form-label">Username</label>
					<div class="col">
						<%= f.text_field :username, class: "form-control" %>
					</div>
				</div>

				<div class="form-group row">
					<label class="col-3 col-form-label">Password</label>
					<div class="col">
						<%= f.password_field :password, class: "form-control", :required => true %>
					</div>
				</div>

				<div class="custom-control custom-switch mb-4">
					<%= f.check_box :admin, :value => true, class: "custom-control-input", id: "customSwitch1" %>
				  <label class="custom-control-label" for="customSwitch1">Admin Access</label>
				</div>



				<%= f.submit class: "btn btn-success btn-sm" %>
				<%= link_to "Back", users_path, :class => "btn btn-outline-primary btn-sm" %>

			<% end %>	
		</div>
	</div>
</div>